## CallHistory

> `/System/Library/PrivateFrameworks/CallHistory.framework/CallHistory`

```diff

-55.400.141.2.3
-  __TEXT.__text: 0x39d7c
+55.500.161.2.1
+  __TEXT.__text: 0x3a160
   __TEXT.__auth_stubs: 0x760
-  __TEXT.__objc_methlist: 0x2f60
-  __TEXT.__cstring: 0x24e9
-  __TEXT.__const: 0x338
-  __TEXT.__oslogstring: 0x4d25
-  __TEXT.__gcc_except_tab: 0x6d0
+  __TEXT.__objc_methlist: 0x36b4
+  __TEXT.__cstring: 0x250a
+  __TEXT.__const: 0x358
+  __TEXT.__oslogstring: 0x4dd9
+  __TEXT.__gcc_except_tab: 0x6f4
   __TEXT.__dlopen_cstrs: 0xf9
-  __TEXT.__unwind_info: 0xf00
+  __TEXT.__unwind_info: 0xf40
   __TEXT.__eh_frame: 0x50
   __TEXT.__objc_classname: 0x64e
-  __TEXT.__objc_methname: 0x9145
+  __TEXT.__objc_methname: 0x916b
   __TEXT.__objc_methtype: 0x11a1
   __TEXT.__objc_stubs: 0x6fc0
   __DATA_CONST.__got: 0x398
-  __DATA_CONST.__const: 0x1200
+  __DATA_CONST.__const: 0x1208
   __DATA_CONST.__objc_classlist: 0x1b8
   __DATA_CONST.__objc_catlist: 0x28
   __DATA_CONST.__objc_protolist: 0xc8
   __DATA_CONST.__objc_imageinfo: 0x8
-  __DATA_CONST.__objc_selrefs: 0x21d0
+  __DATA_CONST.__objc_selrefs: 0x2270
   __DATA_CONST.__objc_protorefs: 0x18
   __DATA_CONST.__objc_superrefs: 0x130
   __AUTH_CONST.__auth_got: 0x3c0
   __AUTH_CONST.__auth_ptr: 0x8
   __AUTH_CONST.__const: 0x380
-  __AUTH_CONST.__cfstring: 0x2c60
-  __AUTH_CONST.__objc_const: 0x9b60
+  __AUTH_CONST.__cfstring: 0x2c80
+  __AUTH_CONST.__objc_const: 0x8eb8
   __AUTH_CONST.__objc_intobj: 0x60
   __AUTH.__objc_data: 0x140
-  __DATA.__objc_ivar: 0x2b0
+  __DATA.__objc_ivar: 0x2b4
   __DATA.__data: 0x9d0
   __DATA.__bss: 0xb0
   __DATA_DIRTY.__objc_data: 0xff0

   - /usr/lib/libSystem.B.dylib
   - /usr/lib/libTelephonyUtilDynamic.dylib
   - /usr/lib/libobjc.A.dylib
-  Functions: 1325
-  Symbols:   1781
-  CStrings:  2556
+  Functions: 1345
+  Symbols:   1802
+  CStrings:  2560
 
CStrings:
+ "55.500.161.2.1"
+ "55.500.161.2.1~2"
+ "Attempting to reconnect to the SyncHelper"
+ "Couldn't get managedObjectModel from db at %{public}@, model at %{public}@, or metadata %{public}@: %{public}@"
+ "Not attempting to reconnect to the SyncHelper because we're missing the %@ entitlement"
+ "Permanent database file doesn't exist; poking sync helper. Error code: %{public}@"
+ "com.apple.CallHistory.sync.allow"
+ "getManagedObjectModelFromDB:orModelURL:orMetadata:"
+ "hasCloudSyncEntitlement"
+ "initWithProcessHandle:"
- "55.400.141.2.3"
- "55.400.141.2.3~1"
- "Couldn't get managedObjectModel from db at %{public}@ or model at %{public}@: %{public}@"
- "Failed to get model because no metadata was provided"
- "getManagedObjectModelFromDB:orModelURL:"
- "modelForDBMetadata:"

```
